name: Workflow 2 - Build and Push Docker Image

on:
  workflow_run:
    workflows:
      - Workflow 1 - Test
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t kaciefrei/mlforproduction:latest .

      - name: Push Docker image
        run: |
          docker push kaciefrei/mlforproduction:latest
